CREATE DATABASE user_record;

USE user_record;

CREATE TABLE users (    id INT AUTO_INCREMENT PRIMARY KEY,    username VARCHAR(255) NOT NULL UNIQUE,    password VARCHAR(255) NOT NULL,    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);，
ALTER TABLE users ADD COLUMN session_id VARCHAR(255);
